language: csharp
mono:
  - latest
solution: DropDownGroupList.sln

install:
  - sudo apt-get install -y mono-complete
  - nuget restore DropDownGroupList.sln
script:
  - xbuild /p:Configuration=Release DropDownGroupList.sln
  - cd DropDownGroupList && ls -a
  - nuget pack Package.nuspec 
  - nuget push *.nupkg $NUGET-API-KEY -verbosity detailed