language: csharp
mono:
  - latest
solution: DropDownGroupList.sln

before-install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -y mono-complete
  - mozroots --import --sync
  - export EnableNuGetPackageRestore=true
  - nuget restore DropDownGroupList.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release DropDownGroupList.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe /DropDownGroupList.Tests/bin/Release/DropDownGroupList.Tests.dll